#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Startup script for TROff - A Multitouch TRON Clone
#
# Copyright (C) 2011 Thomas Schott, <scotty at c-base dot org>
#
# TROff is free software: You can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TROff is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TROff. If not, see <http://www.gnu.org/licenses/>.

import sys

try:
    import troff
except ImportError:
    sys.path = ['..', '/usr/share/games'] + sys.path

    try:
        import troff
    except ImportError:
        sys.stderr.write('ERROR: Cannot find troff package: reinstall the game.\n')
        sys.exit(1)

if __name__ == '__main__':
    troff.TROff.start()
